[build]
  command = "npm run build"
  publish = "build"
  environment = { NODE_ENV = "production" }

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
